version: '3.8'
services:

  cuttlink_db_service:
    image: postgres:15.1-bullseye
    container_name: cuttlink_db
    hostname: postgres
    volumes:
      - /var/lib/postgresql/data/
    environment:
      POSTGRES_DB: cldev
      POSTGRES_USER: cluser
      POSTGRES_PASSWORD: clpassword
    ports:
      - "5432:5432/tcp"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "cluser", "-d", "cldev"]
      interval: 1s
      timeout: 1s
      retries: 42

  cuttlink_migrate_service:
    image: migrate/migrate:latest
    container_name: cuttlink_migrate
    volumes:
      - ./cmd/shortener/migrations:/migrations
    depends_on:
      - cuttlink_db_service
    command: -source=file:///migrations -database postgres://cluser:clpassword@postgres:5432/cldev?sslmode=disable up
    restart: on-failure