version: '3.8'
services:

  cuttlink_dev_dsn:
    image: postgres:15.1-bullseye
    container_name: cuttlink_db
    volumes:
      - /var/lib/postgresql/data/
    environment:
      POSTGRES_DB: cldev
      POSTGRES_USER: cluser
      POSTGRES_PASSWORD: clpassword
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "cluser", "-d", "cldev"]
      interval: 42s
      timeout: 42s
      retries: 42
    ports:
      - 5432:5432